market:
  max_timesteps: 50000
  mode: partial_agents_per_step  # options: single_agent_per_step, partial_agents_per_step, all_agents_per_step
  activation_ratio: 0.1
  fundamental_price: 300.0
  fundamental_volatility: 0.001
  fundamental_drift: 0.00002

agents:
  fundamental_price: 300.0
  count: 100
  noise_std: 0.01
  
  retail_ratio: 0.9
  

  # 全局参考参数
  reference_tau_f: 100         # 用于计算个体 tau_i
  
  strategy_sigma: 0.5

  # 散户设定
  retail:
    fundamental_mu: 1.5
    chartist_mu: 1.0
    noise_mu: 0.5
    initial_stock_max: 100
    bully_noise_amplify: 1.5

  # 机构设定
  institutional:
    fundamental_mu: 3.0
    chartist_mu: 0.5
    noise_mu: 0.3
    initial_stock_max: 5000

  # 网络暴力/情绪机制参数
  emotion_initial_bias: 0.05         # 情绪偏差初始化标准差
  emotion_weight_mu: 1.0          # 情绪权重的波动性


social:
  # 网络暴力机制参数
  enable_cyberbullying: true         # 控制是否启用网络暴力机制
  
  suppression_prob: 0.5              # 被网暴后沉默概率基线
  network_type: small_world          # small_world / random
  average_degree: 6                  # 平均邻居数

  born_bully_ratio: 0.1              # 初始喷子比例
  exposure_threshold: 0.005            # 曝光累积超过此值才视为被网暴
  cooldown_duration: 10               # 喷子攻击后冷却时间
  resilience_growth: 0.01            # 被攻击后心理韧性的增长速度
  exposure_shrink_factor: 0.999        # 每轮恢复压力的速度
  emotion_shrink_factor: 0.8         # 被网暴后情绪极端性减弱因子

  # 正反馈：网暴感染
  enable_bully_infect: true         # 是否允许网暴感染
  bully_infect_prob: 0.05            # 被喷后变喷子的概率
  bully_amplify: 1.5                 # 感染后情绪极端性放大倍数

  # 负反馈：监管与举报
  enable_regulator: false             # 是否启用监管者
  regulator_interval: 10             # 监管者巡视周期（时间步）
  regulator_cooldown: 10             # 监管惩罚的冷却时间
  enable_bully_report: false          # 是否允许被喷者举报
  regulator_report_prob: 0.1         # 举报成功概率
  regulator_report_cooldown: 8       # 举报惩罚的冷却时间
  enable_bully_resilience: true      # 是否允许心理承受能力提升
  sigmoid_k: 1.0                     # sigmoid函数斜率
  max_suppression: 0.95              # 最大沉默概率

orderbook:
  snapshot_interval: 10

simulation:
  random_seed: 40
  log_trades: true
  
  n_simulations: 5 # 配对t检验的次数
